@extends('layouts.site')
@section('title', 'Consent for Laravel - Save time on cookie consent')
@section('description', 'Save time implementing cookie consent in Laravel with a ready-made banner, category preferences and script controls. Includes Google Consent Mode v2, GA4, Google Ads, Meta Pixel and Microsoft Clarity.')
@section('body')
<main id="main-content" tabindex="-1">
    <div id="top" class="section-rail"><span>Cookie consent for Laravel</span><a href="{{ config('site.repository') }}/releases/tag/{{ config('site.release') }}">{{ config('site.release') }} <x-icon name="arrow-up" /></a></div>
    <section class="hero" aria-labelledby="hero-title">
        <div class="hero-copy">
            <div class="release-label"><span class="status-dot" aria-hidden="true"></span> Built for Laravel developers</div>
            <h1 id="hero-title">Save time on<br><span class="text-accent">cookie consent</span></h1>
            <p class="hero-description">Build your Laravel app without creating its cookie banner, preferences and script controls from scratch. GA4, Google Ads, Meta Pixel and Microsoft Clarity are included in version 1.0, with ID-based setup and consent controls.</p>
            <div class="button-row"><a class="button button-primary" href="{{ route('docs.show', 'quick-start') }}">Install the package <x-icon name="arrow-right" /></a><a class="button button-outline" href="{{ route('docs.show', 'introduction') }}">Read the documentation</a></div>
            <div class="hero-install" data-install-command>
                <span class="hero-install-label">Install with Composer</span>
                <div class="hero-install-row">
                    <code data-install-code>composer require {{ config('site.package') }}</code>
                    <button class="hero-install-copy" type="button" aria-label="Copy installation command" data-install-copy hidden>
                        <x-icon name="copy" /><span data-install-copy-label>Copy</span>
                    </button>
                </div>
            </div>
            <p class="hero-note">Open source for PHP 8.3+ and Laravel 12-13,<br>available as a stable Composer package.</p>
        </div>
        <div class="hero-art"><img class="permission-study" src="{{ asset('assets/permission-study.svg') }}" width="620" height="540" alt="Three ordered steps: a visitor chooses, permission is checked, and an allowed script runs."><div class="art-caption"><span>Consent checks handled for you</span><span>Fig. 01</span></div></div>
    </section>
    <div class="spec-strip" aria-label="Package essentials"><span><b>PHP</b> 8.3+</span><span><b>Laravel</b> 12-13</span><span><b>Browser</b> No frontend framework</span><a href="{{ config('site.repository') }}/blob/main/LICENSE.md"><b>License</b> MIT <x-icon name="arrow-up" /></a></div>
    <section id="principles" class="numbered-section" aria-labelledby="principles-title">
        <div class="section-rail"><span>01 / The approach</span><span>Less work on every project</span></div>
        <div class="section-intro"><h2 id="principles-title">Handle the work<br><span class="text-accent">behind the banner</span></h2><p>Designed around EU consent requirements, the package brings the banner, category preferences and withdrawal into one flow you can reuse across Laravel projects.</p></div>
        <div class="principle-grid">
            @foreach([
                ['choice', 'Ready-made UI', 'Use the included banner and category preferences instead of designing, building and maintaining another cookie interface.'],
                ['code', 'Less custom wiring', 'Register your services and use a Blade directive to gate their scripts, so the integration stays inside your existing Laravel views.'],
                ['layers', 'Fits cached pages', 'Keep one cached version of your page while each visitor controls their own consent, avoiding separate page variants and extra cache logic.'],
                ['refresh', 'Changes handled', 'Let visitors reopen their preferences and withdraw consent through the same interface, without building a second flow for changing their minds.'],
                ['keyboard', 'Keyboard support', 'Start with native controls, keyboard navigation and managed focus already in place, reducing the interaction work in your own frontend.'],
                ['globe', 'English and Polish', 'Use the included English and Polish translations, then adapt the copy and service descriptions to your projects.'],
            ] as $index => [$icon, $title, $description])
            <div class="principle"><div class="principle-top"><x-icon :name="$icon" /><span>0{{ $index + 1 }}</span></div><h3>{{ $title }}</h3><p>{{ $description }}</p></div>
            @endforeach
        </div>
    </section>
    <section id="preview" class="numbered-section" aria-labelledby="preview-title">
        <div class="section-rail"><span>02 / The interface</span><span>Adapt it to your project</span></div>
        <div class="section-intro"><h2 id="preview-title">Use the interface<br><span class="text-accent">your project needs</span></h2><p>Choose the position and colors that fit your site, with the banner and category preferences already built. The interactive preview below stores no cookies and loads no trackers.</p></div>
        @include('partials.consent-preview')
    </section>
    <section class="developer-section" aria-labelledby="developer-title"><div class="section-rail"><span>03 / The developer experience</span><span>Setup that fits your workflow</span></div><div class="developer-grid"><div><span class="eyebrow">Configured in your application</span><h2 id="developer-title">Set up consent<br><span class="text-accent">in familiar Laravel code</span></h2><p>Install with Composer, configure your services and add the included Blade components to your layout, then use the script directive to connect each service to visitor consent.</p><a class="button button-accent" href="{{ route('docs.show', 'blade-directives') }}">See the Blade integration <x-icon name="arrow-right" /></a></div><div class="code-example"><div class="code-title"><span>resources/views/layout.blade.php</span><span>Blade</span></div><pre><code class="language-blade">@verbatim&lt;head&gt;
    &lt;x-consent::head /&gt;
&lt;/head&gt;

&lt;x-consent::banner /&gt;

@consent('analytics', 'site-insights')
    &lt;script src="/js/site-insights.js"&gt;&lt;/script&gt;
@endconsent@endverbatim</code></pre><p><span class="status-dot" aria-hidden="true"></span> This script waits for analytics consent.</p></div></div></section>
    <section class="numbered-section" aria-labelledby="integrations-title"><div class="section-rail"><span>04 / The integrations</span><span>From custom scripts to ready-made presets</span></div><div class="section-intro"><h2 id="integrations-title">Add your IDs and<br><span class="text-accent">connect your tools</span></h2><p>GA4, Google Ads, Meta Pixel and Clarity are included in version 1.0. Add your IDs and let the presets handle permission, initialization and withdrawal.</p></div><div class="release-grid"><div class="release-current"><span class="eyebrow">Included in version 1.0</span><h3>Your tools, connected</h3><ul><li><x-icon name="arrow-down-right" />Ready-made banner and category preferences</li><li><x-icon name="arrow-down-right" />Consent-based loading for your own scripts</li><li><x-icon name="arrow-down-right" />Preferences visitors can update at any time</li><li><x-icon name="arrow-down-right" />Configurable positions, colors and wording</li><li><x-icon name="arrow-down-right" />English and Polish included</li><li><x-icon name="arrow-down-right" />Google Consent Mode v2 with Basic and Advanced</li><li><x-icon name="arrow-down-right" />GA4 and Google Ads setup from your IDs</li><li><x-icon name="arrow-down-right" />Meta Pixel and Microsoft Clarity presets</li></ul><a href="{{ route('docs.show', 'introduction') }}">Explore the package <x-icon name="arrow-up" /></a></div><div class="release-planned"><span class="eyebrow">Consent throughout the lifecycle</span><div><strong>Permission before loading</strong><span>Optional scripts wait for a current, valid choice</span></div><div><strong>Events with consent checks</strong><span>Permission checked when called and before dispatch</span></div><div><strong>Withdrawal that takes effect</strong><span>Denied signals, declared cookie cleanup and active preset reload</span></div><a href="{{ route('docs.show', 'integrations') }}">See all included features <x-icon name="arrow-up" /></a></div></div></section>
    <section class="numbered-section" aria-labelledby="guides-title"><div class="section-rail"><span>05 / Getting started</span><span>A clear path from install to launch</span></div><div class="guide-heading"><h2 id="guides-title">Get from install<br><span class="text-accent">to implementation</span></h2><a class="text-link" href="{{ route('docs.index') }}">Read the setup guides <x-icon name="arrow-right" /></a></div><div class="guide-grid">@foreach([['01', 'quick-start', 'Install in Laravel', 'Follow one setup guide from Composer installation to your first working banner and protected script.'], ['02', 'banner-and-theme', 'Configure your interface', 'Find the settings for positioning, colors and copy in one place, so you can match the interface to your project.'], ['03', 'withdrawal', 'Handle changing choices', 'See how the package applies updated preferences and withdrawal, with practical steps for your tracking setup.']] as [$number, $slug, $title, $description])<a class="guide-card" href="{{ route('docs.show', $slug) }}"><span class="eyebrow">Guide / {{ $number }}</span><h3>{{ $title }}</h3><p>{{ $description }}</p><x-icon name="arrow-up" /></a>@endforeach</div></section>
    <section class="faq-section" aria-labelledby="faq-title"><div><span class="eyebrow">Questions before you install</span><h2 id="faq-title">Before your<br> <span class="text-accent">first install</span></h2></div><div class="faq-list"><details><summary>Will it fit my Laravel project?<x-icon name="plus" /></summary><p>Consent supports PHP 8.3+ and Laravel 12-13 and runs inside your application, with installation and configuration covered in the <a href="{{ route('docs.show', 'installation') }}">setup guide</a>.</p></details><details><summary>Can I add Google Analytics or Meta Pixel by ID?<x-icon name="plus" /></summary><p>Yes. Version 1.0 includes GA4, Google Ads, <a href="{{ route('docs.show', 'meta-pixel') }}">Meta Pixel</a> and <a href="{{ route('docs.show', 'microsoft-clarity') }}">Microsoft Clarity</a> presets. Each handles its own consent and initialization.</p></details><details><summary>How does it support EU consent requirements?<x-icon name="plus" /></summary><p>The package provides tools for EU consent requirements, with clear choices, optional categories and consent that visitors can change or withdraw. It gives you the consent mechanism while you supply the <a href="{{ route('docs.show', 'security') }}">service descriptions and privacy information</a> for your application.</p></details><details><summary>What happens when someone changes their mind?<x-icon name="plus" /></summary><p>Visitors can reopen the same preferences screen whenever they need to, and the package applies their updated choices rather than leaving you to build and maintain a separate settings flow.</p></details><details><summary>Do I need another hosted platform?<x-icon name="plus" /></summary><p>Consent is an open-source Composer package that runs in your Laravel application, so you manage the interface and configuration in your own codebase without a separate consent dashboard.</p></details></div></section>
    <section class="closing-section" aria-labelledby="closing-title"><img src="{{ asset('assets/consent-mark.svg') }}" width="72" height="72" alt=""><span class="eyebrow">Open source for Laravel</span><h2 id="closing-title">Get back to<br><span class="text-accent">building your app</span></h2><div class="button-row"><a class="button button-primary" href="{{ route('docs.show', 'installation') }}">Install the package <x-icon name="arrow-right" /></a><a class="button button-outline" href="{{ config('site.repository') }}">View on GitHub <x-icon name="git-fork" /></a></div><p>Use the included consent flow in your next Laravel project and keep more of your time for the features it needs.</p></section>
</main>
@endsection
