@extends('layouts.site')
@section('body')
<main id="main-content" tabindex="-1">
    <div id="top" class="section-rail"><span>Independent package / Laravel</span><a href="{{ config('site.repository') }}/releases/tag/{{ config('site.release') }}">{{ config('site.release') }} <x-icon name="arrow-up" /></a></div>
    <section class="hero" aria-labelledby="hero-title">
        <div class="hero-copy">
            <div class="release-label"><span class="status-dot" aria-hidden="true"></span> A small package. A considered choice.</div>
            <h1 id="hero-title">Every cookie.<br><span class="text-accent">A clear choice.</span></h1>
            <p class="hero-description">Cookie consent that feels at home in Laravel. Give visitors a real choice. Let your scripts respect it.</p>
            <div class="button-row"><a class="button button-primary" href="{{ route('docs.show', 'quick-start') }}">Start building <x-icon name="arrow-right" /></a><a class="button button-outline" href="{{ route('docs.show', 'introduction') }}">Read the documentation</a></div>
            <p class="hero-note">Open source. Framework-free in the browser.<br>Built with care, currently in beta.</p>
        </div>
        <div class="hero-art"><img class="permission-study" src="{{ asset('assets/permission-study.svg') }}" width="620" height="540" alt="Three ordered steps: a visitor chooses, permission is checked, and an allowed script runs."><div class="art-caption"><span>Permission, by design.</span><span>Fig. 01</span></div></div>
    </section>
    <div class="spec-strip" aria-label="Package essentials"><span><b>PHP</b> 8.3+</span><span><b>Laravel</b> 12-13</span><span><b>Browser</b> Zero framework dependencies</span><a href="{{ config('site.repository') }}/blob/main/LICENSE.md"><b>License</b> MIT <x-icon name="arrow-up" /></a></div>
    <section id="principles" class="numbered-section" aria-labelledby="principles-title">
        <div class="section-rail"><span>01 / The approach</span><span>A clear contract</span></div>
        <div class="section-intro"><h2 id="principles-title">Permission before<br><span class="text-accent">execution.</span></h2><p>A banner is the beginning. The useful part is what happens to your scripts before a choice, after acceptance, and when that choice changes.</p></div>
        <div class="principle-grid">
            @foreach([
                ['choice', 'A real choice', 'Accept all, reject optional, or choose by category. Clear actions with equal prominence.'],
                ['code', 'Blade, naturally', 'Wrap scripts in @consent. The browser activates them only when the category is allowed.'],
                ['layers', 'Cache-safe by design', 'The same inert HTML for every visitor. No private preference baked into a shared page.'],
                ['refresh', 'Room to change your mind', 'A small preferences button stays within reach. Active withdrawal defaults to a safe reload.'],
                ['keyboard', 'Considered interactions', 'Native controls, a modal dialog, validated contrast, and deliberate keyboard focus.'],
                ['globe', 'Two languages to start', 'English and Polish out of the box. Translate the interface and describe services in your own words.'],
            ] as $index => [$icon, $title, $description])
            <div class="principle"><div class="principle-top"><x-icon :name="$icon" /><span>0{{ $index + 1 }}</span></div><h3>{{ $title }}</h3><p>{{ $description }}</p></div>
            @endforeach
        </div>
    </section>
    <section id="preview" class="numbered-section" aria-labelledby="preview-title">
        <div class="section-rail"><span>02 / The interface</span><span>Make yourself at home</span></div>
        <div class="section-intro"><h2 id="preview-title">Quiet by nature.<br><span class="text-accent">Yours by configuration.</span></h2><p>Three positions. Your colors. The same clear choices.<br>Try the package interface below. It does not save cookies or load trackers.</p></div>
        @include('partials.consent-preview')
    </section>
    <section class="developer-section" aria-labelledby="developer-title"><div class="section-rail"><span>03 / The developer experience</span><span>Less ceremony, more clarity</span></div><div class="developer-grid"><div><span class="eyebrow">One purpose. One directive.</span><h2 id="developer-title">Write Blade.<br><span class="text-accent">Respect the choice.</span></h2><p>Register your service, add the banner, and wrap its scripts. The browser handles the gate, ordering, and duplicate prevention.</p><a class="button button-accent" href="{{ route('docs.show', 'blade-directives') }}">Meet @consent <x-icon name="arrow-right" /></a></div><div class="code-example"><div class="code-title"><span>resources/views/layout.blade.php</span><span>Blade</span></div><pre><code class="language-blade">@verbatim&lt;head&gt;
    &lt;x-consent::head /&gt;
&lt;/head&gt;

&lt;x-consent::banner /&gt;

@consent('analytics', 'site-insights')
    &lt;script src="/js/site-insights.js"&gt;&lt;/script&gt;
@endconsent@endverbatim</code></pre><p><span class="status-dot" aria-hidden="true"></span> Inert until analytics is accepted.</p></div></div></section>
    <section class="numbered-section" aria-labelledby="roadmap-title"><div class="section-rail"><span>04 / The current chapter</span><span>Honest about what ships</span></div><div class="section-intro"><h2 id="roadmap-title">A solid foundation.<br><span class="text-accent">A deliberate next step.</span></h2><p>The current beta covers the consent foundation, script runtime, and interface. Google Consent Mode v2 and tracker presets are still on the roadmap.</p></div><div class="release-grid"><div class="release-current"><span class="eyebrow">Available in beta.3</span><h3>The consent essentials.</h3><ul><li><x-icon name="arrow-down-right" />Five standard categories, only used ones shown</li><li><x-icon name="arrow-down-right" />Ordered, cache-safe Blade script blocks</li><li><x-icon name="arrow-down-right" />Versioned decisions and active withdrawal</li><li><x-icon name="arrow-down-right" />Three banner positions and validated colors</li><li><x-icon name="arrow-down-right" />English and Polish interface</li></ul><a href="{{ route('docs.show', 'introduction') }}">See what is included <x-icon name="arrow-up" /></a></div><div class="release-planned"><span class="eyebrow">Planned before 1.0</span><div><strong>Google Consent Mode v2</strong><span>GA4 + Google Ads / beta.4</span></div><div><strong>Google Tag Manager</strong><span>GTM integration / beta.5</span></div><div><strong>Meta Pixel + Microsoft Clarity</strong><span>Tracker presets / beta.6</span></div><a href="{{ route('docs.show', 'roadmap') }}">Follow the roadmap <x-icon name="arrow-up" /></a></div></div></section>
    <section class="numbered-section" aria-labelledby="guides-title"><div class="section-rail"><span>05 / Field notes</span><span>From first install to production</span></div><div class="guide-heading"><h2 id="guides-title">Good defaults.<br><span class="text-accent">Clear documentation.</span></h2><a class="text-link" href="{{ route('docs.index') }}">All documentation <x-icon name="arrow-right" /></a></div><div class="guide-grid">@foreach([['01', 'quick-start', 'Your first consent gate', 'From installation to a working banner and your first protected script.'], ['02', 'banner-and-theme', 'Make it your own', 'Position, colors, policy links, translations, and published views.'], ['03', 'withdrawal', 'Plan for a changed mind', 'Safe reloads, cooperative cleanup, and first-party cookie removal.']] as [$number, $slug, $title, $description])<a class="guide-card" href="{{ route('docs.show', $slug) }}"><span class="eyebrow">Guide / {{ $number }}</span><h3>{{ $title }}</h3><p>{{ $description }}</p><x-icon name="arrow-up" /></a>@endforeach</div></section>
    <section class="faq-section" aria-labelledby="faq-title"><div><span class="eyebrow">A few things to know</span><h2 id="faq-title">Before you<br><span class="text-accent">begin.</span></h2></div><div class="faq-list"><details><summary>Which Laravel versions are supported?<x-icon name="plus" /></summary><p>The package targets PHP 8.3+ and Laravel 12-13. Check the <a href="{{ route('docs.show', 'installation') }}">installation guide</a> for the current beta installation and compatibility notes.</p></details><details><summary>Does it include Google or Meta integrations?<x-icon name="plus" /></summary><p>Not yet. Beta.3 supplies the consent foundation and generic script gate. Google Consent Mode v2, GA4, Google Ads, GTM, Meta Pixel, and Clarity are planned. See the <a href="{{ route('docs.show', 'roadmap') }}">roadmap</a>.</p></details><details><summary>Does a banner make my site compliant?<x-icon name="plus" /></summary><p>A banner alone cannot establish legal compliance. Your site must correctly describe purposes, block all relevant processing, provide policy information, and honor withdrawal. The package is tooling, currently in beta. Read <a href="{{ route('docs.show', 'security') }}">security and privacy</a> and <a href="{{ route('docs.show', 'accessibility') }}">accessibility</a> before deployment.</p></details><details><summary>Can visitors change their choice later?<x-icon name="plus" /></summary><p>Yes. A compact preferences button appears after a decision. You can also open preferences through the browser API. Revoking an already active category reloads by default because removing a script element cannot stop running code.</p></details><details><summary>Is this a hosted service?<x-icon name="plus" /></summary><p>No. It is a Composer package installed in your Laravel application. It has no dashboard, tracking backend, or required third-party consent service.</p></details></div></section>
    <section class="closing-section" aria-labelledby="closing-title"><img src="{{ asset('assets/consent-mark.svg') }}" width="72" height="72" alt=""><span class="eyebrow">Open source / Made for Laravel</span><h2 id="closing-title">Build with care.<br><span class="text-accent">Start with consent.</span></h2><div class="button-row"><a class="button button-primary" href="{{ route('docs.show', 'installation') }}">Install the beta <x-icon name="arrow-right" /></a><a class="button button-outline" href="{{ config('site.repository') }}">Explore the source <x-icon name="git-fork" /></a></div><p>No account. No dashboard. Your application, your choices.</p></section>
</main>
@endsection
